local: en
genes_alleles:
  # Each allele is NAME, value, dominance

  BeeSpecies:
    # first era
    - [FOREST, 1, True]
    - [MEADOWS, 2, True]
    - [COMMON, 3, True]
    - [CULTIVATED, 4, True]
    - [NOBLE, 5, False]
    - [MAJESTIC, 6, True]
    - [IMPERIAL, 7, False]
    - [DILIGENT, 8, False]
    - [UNWEARY, 9, True]
    - [INDUSTRIOUS, 10, False]

    # second era
    - [TECHNOLOGICAL, 11, True]
    - [FRAME, 12, True]
    - [RESOURCEFUL, 13, False]
    - [FERTILE, 14, False]
    - [LIVELY, 15, False]
    - [MINING, 16, True]
    - [ROCKY, 17, False]
    - [FERROUS, 18, True]
    - [AURIC, 19, False]
    - [AWARE, 20, True]
    - [SMART, 21, False]
    - [CONSCIOUS, 22, True]
    - [SENTIENT, 23, False]
    - [MANUFACTURING, 24, True]
    - [FABRICATING, 25, False]
    - [ASSEMBLING, 26, True]
    - [AUTOMATING, 27, False]
    - [EXCITED, 28, True]
    - [ENERGETIC, 29, False]
    - [AMPED, 30, True]
    - [ELECTRIC, 31, False]

    # third era: tbd

  BeeFertility:
    - [ONE, 1, False]
    - [TWO, 2, True]
    - [THREE, 3, False]
    - [FOUR, 4, False]

  BeeLifespan:
    - [LONGEST, 14, False]
    - [LONGER, 12, False]
    - [LONG, 10, False]
    - [ELONGATED, 9, False]
    - [NORMAL, 8, False]
    - [SHORTENED, 7, False]
    - [SHORT, 6, True]
    - [SHORTER, 4, True]
    - [SHORTEST, 2, False]

  BeeSpeed:
    - [FASTEST, 1.7, False]
    - [FASTER, 1.4, False]
    - [FAST, 1.2, False]
    - [NORMAL, 1.0, False]
    - [SLOW, 0.8, False]
    - [SLOWER, 0.6, True]
    - [SLOWEST, 0.3, True]

default_genes:
  FOREST:
    fertility: 2
    lifespan: SHORT
    speed: SLOWEST
  MEADOWS:
    fertility: 2
    lifespan: SHORT
    speed: SLOWEST
  COMMON:
    fertility: 2
    lifespan: SHORT
    speed: SLOWER
  CULTIVATED:
    fertility: 2
    lifespan: SHORTER
    speed: SLOW

  NOBLE:
    fertility: 2
    lifespan: SHORTENED
    speed: SLOWER
  MAJESTIC:
    fertility: 2
    lifespan: NORMAL
    speed: SLOWEST
  IMPERIAL:
    fertility: 3
    lifespan: NORMAL
    speed: SLOWEST

  DILIGENT:
    fertility: 2
    lifespan: SHORT
    speed: SLOWER
  UNWEARY:
    fertility: 2
    lifespan: SHORTER
    speed: SLOW
  INDUSTRIOUS:
    fertility: 2
    lifespan: SHORTEST
    speed: NORMAL


  TECHNOLOGICAL:
    fertility: 1
    lifespan: SHORT
    speed: SLOWEST

  FRAME:
    fertility: 2
    lifespan: SHORT
    speed: SLOWEST
  RESOURCEFUL:
    fertility: 2
    lifespan: SHORT
    speed: SLOWEST
  FERTILE:
    fertility: 2
    lifespan: SHORT
    speed: SLOWEST
  LIVELY:
    fertility: 2
    lifespan: SHORT
    speed: SLOWEST

  MINING:
    fertility: 3
    lifespan: SHORT
    speed: SLOWER
  ROCKY:
    fertility: 3
    lifespan: SHORT
    speed: SLOWER
  FERROUS:
    fertility: 2
    lifespan: SHORTER
    speed: SLOWEST
  AURIC:
    fertility: 2
    lifespan: SHORTER
    speed: SLOWEST

  AWARE:
    fertility: 2
    lifespan: ELONGATED
    speed: SLOWEST
  SMART:
    fertility: 2
    lifespan: ELONGATED
    speed: SLOWEST
  CONSCIOUS:
    fertility: 2
    lifespan: ELONGATED
    speed: SLOWEST
  SENTIENT:
    fertility: 2
    lifespan: LONG
    speed: SLOWEST

  MANUFACTURING:
    fertility: 2
    lifespan: SHORTER
    speed: SLOW
  FABRICATING:
    fertility: 2
    lifespan: SHORTEST
    speed: NORMAL
  ASSEMBLING:
    fertility: 2
    lifespan: SHORTEST
    speed: FAST
  AUTOMATING:
    fertility: 2
    lifespan: SHORTEST
    speed: FAST

  EXCITED:
    fertility: 2
    lifespan: SHORTER
    speed: SLOWER
  ENERGETIC:
    fertility: 2
    lifespan: SHORTER
    speed: SLOWER
  AMPED:
    fertility: 2
    lifespan: SHORTEST
    speed: SLOW
  ELECTRIC:
    fertility: 2
    lifespan: SHORTEST
    speed: SLOW

basic_species:
  - FOREST
  - MEADOWS

mutations:
  BeeSpecies:
    - [FOREST, MEADOWS, COMMON, 0.15]
    - [FOREST, COMMON, CULTIVATED, 0.12]
    - [COMMON, MEADOWS, CULTIVATED, 0.12]

    - [CULTIVATED, COMMON, NOBLE, 0.1]
    - [CULTIVATED, NOBLE, MAJESTIC, 0.08]
    - [CULTIVATED, COMMON, DILIGENT, 0.1]

    - [MAJESTIC, NOBLE, IMPERIAL, 0.08]
    - [CULTIVATED, DILIGENT, UNWEARY, 0.08]
    - [UNWEARY, DILIGENT, INDUSTRIOUS, 0.08]

    - [INDUSTRIOUS, IMPERIAL, TECHNOLOGICAL, 0.15]

    - [TECHNOLOGICAL, CULTIVATED, FRAME, 0.1]
    - [TECHNOLOGICAL, FRAME, RESOURCEFUL, 0.1]
    - [TECHNOLOGICAL, FRAME, FERTILE, 0.1]
    - [TECHNOLOGICAL, FRAME, LIVELY, 0.1]

    - [TECHNOLOGICAL, CULTIVATED, MINING, 0.1]
    - [TECHNOLOGICAL, MINING, ROCKY, 0.1]
    - [MINING, ROCKY, FERROUS, 0.1]
    - [ROCKY, FERROUS, AURIC, 0.1]

    - [TECHNOLOGICAL, CULTIVATED, AWARE, 0.1]
    - [TECHNOLOGICAL, AWARE, SMART, 0.1]
    - [AWARE, SMART, CONSCIOUS, 0.1]
    - [SMART, CONSCIOUS, SENTIENT, 0.1]

    - [TECHNOLOGICAL, CULTIVATED, MANUFACTURING, 0.1]
    - [TECHNOLOGICAL, MANUFACTURING, FABRICATING, 0.1]
    - [MANUFACTURING, FABRICATING, ASSEMBLING, 0.1]
    - [FABRICATING, ASSEMBLING, AUTOMATING, 0.1]

    - [TECHNOLOGICAL, CULTIVATED, EXCITED, 0.1]
    - [TECHNOLOGICAL, EXCITED, ENERGETIC, 0.1]
    - [EXCITED, ENERGETIC, AMPED, 0.1]
    - [ENERGETIC, AMPED, ELECTRIC, 0.1]

# maybe calculate based on the mutations?
tier:
  BeeSpecies:
    FOREST: 0
    MEADOWS: 0
    COMMON: 1
    CULTIVATED: 2
    NOBLE: 3
    MAJESTIC: 4
    IMPERIAL: 5
    DILIGENT: 3
    UNWEARY: 4
    INDUSTRIOUS: 5

    TECHNOLOGICAL: 6
    FRAME: 7
    RESOURCEFUL: 8
    FERTILE: 8
    LIVELY: 8
    MINING: 7
    ROCKY: 8
    FERROUS: 9
    AURIC: 10
    AWARE: 7
    SMART: 8
    CONSCIOUS: 9
    SENTIENT: 10
    MANUFACTURING: 7
    FABRICATING: 8
    ASSEMBLING: 9
    AUTOMATING: 10
    EXCITED: 7
    ENERGETIC: 8
    AMPED: 9
    ELECTRIC: 10

production_modifier: 1
resources:
  - WOOD
  - FLOWERS
  - HONEY
  - STINGER
  - STRING
  - ROYAL_JELLY
  - POLLEN_CLUSTER
  - TOOL
  - FRAME
  - ACCELERATIUM
  - PHEROMONE
  - AMBROSIA
  - PICKAXE
  - STONE
  - IRON
  - GOLD
  - REACTION
  - THOUGHT
  - MIND
  - KNOWLEDGE
  - WHEEL
  - GEAR
  - SHAFT
  - MECHANISM
  - ELECTRON
  - PROTON
  - FORCE
  - ELECTRICITY

# [add_or_subtract, amt]
# add_or_subtract: 1 to add, -1 to subtract
# amt: if add, this will be modified by building modifiers
#      if sub, this is a flat value to be subtracted from resources
products: 
  FOREST: # subbed by AWARE tree
    WOOD: [1, 5]
  MEADOWS: # subbed by AWARE tree
    FLOWERS: [1, 5]
  COMMON:
    HONEY: [1, 2.5]
  CULTIVATED: # subbed by TECHNOLOGICAL and AUTOMATING tree
    HONEY: [1, 5]
  NOBLE:
    STINGER: [1, 1]
  MAJESTIC:
    STINGER: [1, 2]
  IMPERIAL:
    ROYAL_JELLY: [1, 1]
  DILIGENT:
    STRING: [1, 1]
  UNWEARY:
    STRING: [1, 2]
  INDUSTRIOUS:
    POLLEN_CLUSTER: [1, 1]

  TECHNOLOGICAL:
    TOOL: [1, 1]
    HONEY: [-1, 1]

  FRAME:
    FRAME: [1, 0.1]
    TOOL: [-1, 1]
  RESOURCEFUL:
    ACCELERATIUM: [1, 0.1]
    STINGER: [-1, 2]
    STRING: [-1, 2]
  FERTILE:
    PHEROMONE: [1, 0.1]
    ROYAL_JELLY: [-1, 1]
  LIVELY:
    AMBROSIA: [1, 0.1]
    POLLEN_CLUSTER: [-1, 1]

  MINING: # MINING tree will sub more and more pickaxes
    PICKAXE: [1, 1]
    TOOL: [-1, 1]
  ROCKY:
    STONE: [1, 1]
    PICKAXE: [-1, 1]
  FERROUS:
    IRON: [1, 1]
    STONE: [-1, 1]
    PICKAXE: [-1, 1]
  AURIC:
    GOLD: [1, 1]
    IRON: [-1, 1]
    PICKAXE: [-1, 2]

  AWARE: # SENTIENT tree requires base resources, next requires more of previous
    REACTION: [1, 1]
    FLOWERS: [-1, 1]
    HONEY: [-1, 2]
  SMART:
    THOUGHT: [1, 1]
    REACTION: [-1, 2]
  CONSCIOUS:
    MIND: [1, 1]
    THOUGHT: [-1, 2]
  SENTIENT:
    KNOWLEDGE: [1, 1]
    MIND: [-1, 2]

  MANUFACTURING: # AUTOMATING tree final resource requires all of previous
    WHEEL: [1, 1]
    WOOD: [-1, 1]
    HONEY: [-1, 2]
  FABRICATING:
    GEAR: [1, 1]
    WHEEL: [-1, 1]
  ASSEMBLING:
    SHAFT: [1, 1]
    WOOD: [-1, 1]
  AUTOMATING:
    MECHANISM: [1, 1]
    WHEEL: [-1, 1]
    GEAR: [-1, 1]
    SHAFT: [-1, 1]

  EXCITED: # I didn't come up with anything unique
    ELECTRON: [1, 1]
    STRING: [-1, 1]
    STINGER: [-1, 1]
  ENERGETIC:
    PROTON: [1, 1]
    STRING: [-1, 1]
    STINGER: [-1, 1]
  AMPED:
    FORCE: [1, 1]
    ELECTRON: [-1, 1]
    PROTON: [-1, 1]
  ELECTRIC:
    ELECTRICITY: [1, 1]
    FORCE: [-1, 2]

amount_needed_to_analyze:
  FOREST: 10
  MEADOWS: 10
  COMMON: 50
  CULTIVATED: 100
  NOBLE: 50
  MAJESTIC: 50
  IMPERIAL: 100
  DILIGENT: 50
  UNWEARY: 50
  INDUSTRIOUS: 100
  TECHNOLOGICAL: 100
  FRAME: 500
  RESOURCEFUL: 50
  FERTILE: 50
  LIVELY: 50
  MINING: 100
  ROCKY: 100
  FERROUS: 100
  AURIC: 50
  AWARE: 100
  SMART: 100
  CONSCIOUS: 100
  SENTIENT: 50
  MANUFACTURING: 100
  FABRICATING: 100
  ASSEMBLING: 100
  AUTOMATING: 50
  EXCITED: 100
  ENERGETIC: 100
  AMPED: 100
  ELECTRIC: 50

colors:
  FOREST: "#b5fde8ff"
  MEADOWS: "#ffb69dff"
  COMMON: "#eee9deff"
  CULTIVATED: "#9eb7f8ff"
  NOBLE: "#fff79dff"
  MAJESTIC: "#e05020ff"
  IMPERIAL: "#f1f8a0ff"
  DILIGENT: "#f9a3e8ff"
  UNWEARY: "#c6ffc0ff"
  INDUSTRIOUS: "#fdffffff"

  TECHNOLOGICAL: "#EF5200ff"

  FRAME: "#574034ff" # done
  RESOURCEFUL: "#05C9F0ff"
  FERTILE: "#EF0566ff"
  LIVELY: "#F0D905ff"

  MINING: "#333229ff" # done
  ROCKY: "#575434ff"
  FERROUS: "#8A8337ff"
  AURIC: "#F0DD01ff"

  AWARE: "#29605aff" # done
  SMART: "#449f97ff"
  CONSCIOUS: "#51bfb5ff"
  SENTIENT: "#6cfff1ff"

  MANUFACTURING: "#2B2933ff" # done
  FABRICATING: "#3A3457ff"
  ASSEMBLING: "#3520A0ff"
  AUTOMATING: "#2300D3ff"

  EXCITED: "#775448ff" # done
  ENERGETIC: "#703F2Dff"
  AMPED: "#A34321ff"
  ELECTRIC: "#D63900ff"